### ISSUE TITLE
this is a outdated version of the blocker

### ISSUE THREAD

**Issue by R6IIIXIII** [HXCHS/HackersX-Unblocked-Websites#12]
the blocker does not work with the new securly. securely usually updates that extention A LOT. So for this to work you would need to have a blocker that actually blocks this new securely lmk when you do this.

**Comment by HXCHS** [comment]
It still works for me? Or I just havnt been updated. Ill update it though. Ty

**Comment by R6IIIXIII** [comment]
yea this started in december somthing but ive been trying to figure out why its not working becuase no way securly made a hole ass new blocker AGAIN.

**Comment by R6IIIXIII** [comment]
and i also understand that your like not the original owner of this but please try to find a updated blocker because no mater what you run the file through it will say that you dont have the right version. please try to do something about this thank you.

**Comment by HXCHS** [comment]
It works for my schools chromebooks version, do you know what version your chromebook is?

**Comment by R6IIIXIII** [comment]
how do i know what version? i just know that i have a touch screen

**Comment by EEEEHI** [comment]
I got a new chromebook and it doesn't work anymore on C734 acer.

**Comment by OrangeThunderFire** [comment]
HCXCHS I think you haven't updated, I didn't update until today because its super laggy when not updated, and then it didn't work anymore. I don't know about version, but I think we are all on the latest update of securly, if you know the owner or know how the code works, please fix like I know already 20 people who depend on this, I see you are active in trying to fix, please do I play finalearth.com, and without this I can't access it and will prob lose at it. Please fix.
